# Generated by Django 5.0.6 on 2024-05-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='')),
                ('ativo', models.BooleanField(default=False)),
                ('link_destino', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
    ]
