# Generated by Django 5.0.6 on 2024-05-24 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_banner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemPedido',
            new_name='Carrinho',
        ),
    ]
