# Generated by Django 5.0.6 on 2024-05-28 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_itempedido_carrinho'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='sobrenome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
