# Generated by Django 5.0.6 on 2024-05-28 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lastname',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
