# Generated by Django 5.0.6 on 2024-05-28 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja_app', '0002_user_lastname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='lastname',
            new_name='nome',
        ),
    ]
